version: '3.9'

services:
  order-service:
    build: ./
    environment:
      DB_HOST: "postgres"
      DB_PORT: "5432"
      PORT: "8085"
      OTEL_TRACES_EXPORTER: "logging"
      OTEL_METRICS_EXPORTER: "logging"
      OTEL_LOGS_EXPORTER: "logging"
    ports:
        - '8084:8084'
    networks:
      - order-services-network
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: opentelemetry
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    networks:
      - order-services-network

networks:
  order-services-network:
    driver: bridge