version: '3.9'

services:
  order-service:
    build: ./
    environment:
      HOST: postgres
    ports:
        - '8084:8084'
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: opentelemetry
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"