server:
  port: 8084

spring:
  application:
    name: order service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/opentelemetry
    username: username
    password: password

  sql:
    init:
      mode: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true
        default_schema: orders
logging:
  level:
    root: debug