server:
  port: 8084

spring:
  application:
    name: order service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${HOST:localhost}:5434/opentelemetry
    username: username
    password: password

  sql:
    init:
      mode: never

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        default_schema: orders
logging:
  level:
    root: debug